/*create table person(
id INTEGER not NULL ,
 name varchar(250)not NULL,
 location varchar(250),
birth_date TIMESTAMP ,
primary key(id)
);

create table books(
book_id INTEGER not NULL ,
name VARCHAR(250)not NULL,
person_id INTEGER,
primary key(book_id),
FOREIGN KEY(person_id) REFERENCES person(id)
);*/

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(10001,'GEORGE','KALLITHEA',SYSDATE());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(10002,'JIM','FALIR0',SYSDATE());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(10003,'PETER','LIKOVRISI',SYSDATE());

INSERT INTO BOOKS (BOOK_ID,NAME,PERSON_ID) VALUES (1,'FILOSOPHY',10001);
INSERT INTO BOOKS (BOOK_ID,NAME,PERSON_ID) VALUES (2,'MATHEMATICS',10001);
INSERT INTO BOOKS (BOOK_ID,NAME,PERSON_ID) VALUES (3,'GYMNASTICS',10003);
